name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  package-ci:
    uses: mhold3n/server/.github/workflows/reusable-python-package-ci.yml@77eea34329f1d292afbfe031dbe3877837c16305
    secrets: inherit
    with:
      python-version: "3.11"
      extras-name: dev
      mypy-target: src
      mypy-extra-args: "--strict"
      ruff-paths: .
      pytest-args: pytest -q
      run-mypy: false
